version: "3.8"

services:

<<<<<<< HEAD
=======
    ansible:
        build:
            dockerfile: ansible/Dockerfile
        networks:
            - bookshelf

>>>>>>> cea1434ee75169110fd7ed11f553aa230f6a6f3b
    bookshelf0:
        build:
            dockerfile: server/Dockerfile
            context: .
        ports:
            - "23:22"
        networks:
            - bookshelf          

    bookshelf1:
        build:
            dockerfile: server/Dockerfile
            context: .
        ports:
            - "24:22"
        networks:
            - bookshelf

    bookshelf2:
<<<<<<< HEAD
      build:
        dockerfile: server/Dockerfile
        context: .
      ports:
        - "25:22"

    bookshelf3:
      build:
        dockerfile: server/Dockerfile
        context: .
      ports:
        - "26:22"

    bookshelf4:
      build:
        dockerfile: server/Dockerfile
        context: .
      ports:
        - "27:22"     

# networks:
=======
        build:
            dockerfile: server/Dockerfile
            context: .
        ports:
            - "25:22"
        networks:
            - bookshelf

    bookshelf3:
        build:
            dockerfile: server/Dockerfile
            context: .
        ports:
            - "26:22"
        networks:
            - bookshelf

    bookshelf4:
        build:
            dockerfile: server/Dockerfile
            context: .
        ports:
            - "27:22"
        networks:
            - bookshelf

networks:
    bookshelf:
        driver: bridge
>>>>>>> cea1434ee75169110fd7ed11f553aa230f6a6f3b

  # nginx:
  #     image: nginx:latest
  #     volumes:
  #         - ./nginx/ssl:/etc/nginx/ssl
  #         - ./nginx/logs:/var/log/nginx
  #         - ./nginx/upstream.conf:/etc/nginx/conf.d/default.conf
  #         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     ports:
  #         - "${NGINX_PORT}:80"          
  #     networks:
  #         - backend        
   